### ISSUE TITLE
Support for the MQTT trigger

### ISSUE THREAD

**Issue by jpflueger** [spinkube/containerd-shim-spin#111]
It would be great to have support for the [spinkube/spin-trigger-mqtt](https://github.com/spinkube/spin-trigger-mqtt) in the containerd shim as one of the available triggers.

**Comment by Mossaka** [comment]
Sounds good to me. 

I wonder if we need a better story for installing spin plugins in the spin shim, a more dynamic approach such as placing the plugin tar in a path where the spin shim could unpack and load into spin engine dynamically. Ofc this could be integrated in runtime-class-manager.

**Comment by kate-goldenring** [comment]
I'm happy to work on adding support for this
