### ISSUE TITLE
Cut new release targeting Spin v2.5

### ISSUE THREAD

**Issue by radu-matei** [spinkube/containerd-shim-spin#137]
The latest release of the shim is using Spin v2.4. There is a user request for a new release of the shim targeting Spin v2.5.

**Comment by calebschoepp** [comment]
It'd be nice to go straight to `v2.5.1` to get OTel support. FWIW looks like the shim is already pointed at `v2.5.1`.

**Comment by radu-matei** [comment]
Yeah, I was assuming that since the shim already uses v2.5.1.

**Comment by kate-goldenring** [comment]
This release will also bring in support for K0s in the node installer. Should we also consider resolving https://github.com/spinkube/containerd-shim-spin/issues/52 first by handling the listen address port?

**Comment by kate-goldenring** [comment]
I think as a preliminary step we should cut releases of the SQS and command triggers. I can do that today

**Comment by radu-matei** [comment]
The main question I have coming back to this thread is whether we should wait for Spin v2.6?

**Comment by calebschoepp** [comment]
How urgent is the user request? If it isn't that urgent I would just opt to save the work and jump directly to v2.6.

**Comment by seungjin** [comment]
Can we have a canary version of this shim updating every night?

**Comment by Mossaka** [comment]
The main branch was bumped to Spin v2.6. Can have a new release. 

> Can we have a canary version of this shim updating every night?
Sounds good to me

**Comment by kate-goldenring** [comment]
Closing as shim v0.15.0 was released which points to spin `v2.6`
