### ISSUE TITLE
node-installer: k0s single node

### ISSUE THREAD

**Issue by vdice** [spinkube/containerd-shim-spin#153]
I am new to k0s but was running through the motions of installing the shim on a local k0s cluster, thanks to the support added recently in https://github.com/spinkube/containerd-shim-spin/pull/135

I followed the k0s quickstart [here](https://docs.k0sproject.io/stable/install/) and went with the  easy-mode, `single node k0s that includes the controller and worker functions with the default configuration`

In this mode, the systemctl service is `k0scontroller` rather than `k0sworker`.  The latter is used in the node-installer logic [here](https://github.com/spinkube/containerd-shim-spin/blob/main/node-installer/script/installer.sh#L58).  Therefore, shim installation fails with the following:

```
$ k -n kwasm logs pod/lima-shimvm-provision-kwasm-nzwz6
Failed to restart k0sworker.service: Unit k0sworker.service not found.
```

Here's the systemctl service I see:
```
$ systemctl status k0sworker
Unit k0sworker.service could not be found.
$ systemctl status k0scontroller
● k0scontroller.service - k0s - Zero Friction Kubernetes
     Loaded: loaded (/etc/systemd/system/k0scontroller.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-06-28 10:56:04 MDT; 8min ago
     ...
```

Do we want to update the node-installer logic to support this single-node scenario?  Or document that a multi-node setup (i.e. with an additional worker node/systemctl service) is required?  cc @Ajpantuso

**Comment by Ajpantuso** [comment]
I think it's sensible to check if it's a worker or a controller with something like:
```bash
if systemctl list-units | grep -q k0sworker; then
...
else
...
fi
```
