### ISSUE TITLE
Precompilation breaks Spin applications distributed in `scratch` containers

### ISSUE THREAD

**Issue by radu-matei** [spinkube/containerd-shim-spin#31]
Building a branch of #16 and running with the default sample for distributing apps in `scratch` containers, `ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:v0.10.0`:

```
$ ctr run --rm --net-host --runtime io.containerd.spin.v2 ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:v0.10.0 test shim.wasm

time="2024-03-08T12:29:33.665338975Z" level=info msg="found manifest with WASM OCI image format"

time="2024-03-08T12:29:33.665495766Z" level=info msg="precompiling layers for image: ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:v0.10.0"
```

The precompilation support assumes the content that should be precompiled is its own layer, which is not the case with Spin applications distributed as (actual) container images.

This raises two options:

* only allow apps distributed with `spin registry push` to run with this version of the shim
* not merge the precompilation support yet and figure out a way to opt out of precompilation

If we continue to support apps distributed in `scratch` containers, those will likely never support precompilation (or not without effort that I would argue is not necessary -- this is of course my opinion).

**Comment by endocrimes** [comment]
> not merge the precompilation support yet and figure out a way to opt out of precompilation

this gets my vote - although I think it is probably worth the effort of supporting precompilation for them.

**Comment by radu-matei** [comment]
Fix (by skipping precompilation for scratch containers) in https://github.com/spinkube/containerd-shim-spin/pull/32.
