### ISSUE TITLE
Add a version flag to the containerd-shim-spin binary

### ISSUE THREAD

**Issue by kate-goldenring** [spinkube/containerd-shim-spin#33]
Right now you have to check the shasum of the binary to determine version. Would be optimal to be able to run `containerd-shim-spin-v2 --version`

**Comment by endocrimes** [comment]
Printing version information during startup would also be excellent

**Comment by radu-matei** [comment]
We need to be careful here to not interfere with the assumption that the shim needs to print a socket on stdout.

**Comment by Mossaka** [comment]
Don't we already have it?

```
/usr/local/bin/containerd-shim-spin-v2 -v      
containerd-shim-spin-v2:
  Runtime: spin
  Version: 0.11.1
  Revision: 6c507e030dd17b3.m

```

**Comment by jsturtevant** [comment]
I think this is already supported with container-wasm-rust: https://github.com/containerd/runwasi/blob/d9a256fa6d551e63fe16158d964d4d7c032f2109/crates/containerd-shim-wasm/src/sandbox/cli.rs#L54

**Comment by jsturtevant** [comment]
:-) we posted at similar times, it does look like it has this already: https://github.com/spinkube/containerd-shim-spin/blob/1f8c36a8256106a5cf2c6d77f036c89eed32901e/containerd-shim-spin/src/main.rs#L15-L22

**Comment by kate-goldenring** [comment]
Thanks @jsturtevant and @Mossaka. Closing as resolved
