### ISSUE TITLE
Pods stuck in terminating state

### ISSUE THREAD

**Issue by radu-matei** [spinkube/containerd-shim-spin#39]
On some Kubernetes distributions we are still experiencing pods being stuck in "Terminating" state.

https://github.com/spinkube/containerd-shim-spin/pull/23 apparently was only half of the issue — the shim actually being able to handle SIGTERM; what we appear to experience is the shim not receiving the signal altogether, and that is currently being investigated in https://github.com/containerd/runwasi/issues/418.

Filing this to track the fix in the Spin shim.

**Comment by Mossaka** [comment]
Follow up - we should add integraion tests on CI to test spin shim on k3s clusters

**Comment by Mossaka** [comment]
Follow up [Open Discussion]: when the shim ttrpc server panics / crashes, there should be a way to tell from containerd or shim logs?

**Comment by rajatjindal** [comment]
> Follow up - we should add integraion tests on CI to test spin shim on k3s clusters

will adding the steps I listed out to reproduce the [issue here](https://github.com/containerd/runwasi/issues/418#issuecomment-1992236570) enough or we need it to be more involved?

I am happy to add those steps as a CI test here

**Comment by Mossaka** [comment]
@rajatjindal Yes, I was thinking about adding it as a CI step. Something similar to https://github.com/containerd/runwasi/blob/main/test/k3s/bootstrap.sh

**Comment by rajatjindal** [comment]
Hi @Mossaka, thank you for the pointer.

can I take up the task to add tests for k3s?

re: ttrpc issue. given how critical that workflow is, I think we should have logging in the containerd logs. Also it would be nice to have a mechanism to healthcheck it and possibly restart automatically if possible.

**Comment by rajatjindal** [comment]
In this [draft PR](https://github.com/spinkube/containerd-shim-spin/pull/46), I've attempted to add a very simple test to exercise delete operation using the existing setup for integration tests. 

One thing I could not decide on is to have a script for this or should this be added in rust integration tests suite? do we have any preference of doing one over the other?

It currenty fails as expected (pending fix for this issue being merged). An example run could be found [here](https://github.com/spinkube/containerd-shim-spin/actions/runs/8312763866/job/22748233973)
