### ISSUE TITLE
Add instructions on running locally

### ISSUE THREAD

**Issue by radu-matei** [spinkube/containerd-shim-spin#42]
We have instructions for how to setup your local environment to test this directly with `ctr` and Containerd, as well as with K3s.

To help future contributors (and Radu from 2 weeks in the future), we should write the instructions in a doc section — I don't have an opinion between this repo or the docs repo.

Thoughts?

**Comment by Mossaka** [comment]
Historically I've been pointing people to look up the Makefile / GH Action for how to setup local environments. I think having some docs would be a good idea. I am fine with either leaving the doc section in this repo or the docs repo.

**Comment by jsturtevant** [comment]
Are the docs https://github.com/spinkube/documentation?  If so +1 to adding it there under a "Contributor" (or something similar) section and linking from the readme
