### ISSUE TITLE
Create new release for the Spin shim with outbound MQTT support

### ISSUE THREAD

**Issue by radu-matei** [spinkube/containerd-shim-spin#94]
https://github.com/spinkube/containerd-shim-spin/pull/55 added support for Spin 2.4, which introduced outbound MQTT support.

To support this workload (and to avoid the scenario for the Python SDK with apps failing to start because of the missing MQTT import — https://github.com/spinkube/spin-operator/issues/202#issuecomment-2070544367), we should create a new release of the shim.

**Comment by vdice** [comment]
The shim is now on Spin 2.6.  Should outbound MQTT _just work_ now?
